# Generated by Django 2.2.4 on 2021-02-10 08:59

from django.db import migrations


def load_objects(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats:
        Owner.objects.get_or_create(full_name=flat.owner,
                                    phone_number=flat.owners_phonenumber,
                                    pure_phone_number=flat.owner_pure_phone,
                                    )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(load_objects)
    ]
